<?php

global $perfanal_url;
$perfanal_url='perfanal_v2/';

function Performance_Anaylsis_perm()
{
   return array('layout performance analysis (everyone)','access performance analysis', 'admin performance analysis','aditional performance analysis');
}

function performance_anaylsis_menu()
{
	
	global $perfanal_url;
	$domain = $_SERVER["SERVER_NAME"];

   $items = array();

	    require($perfanal_url.'main_config.php');

	    foreach($sites as $domain_reg=>$data)
		 {
			
			 if(preg_match('/'.$domain_reg.'/',$domain))
			 {
				 foreach($data as $url_reg=>$conf)
				 {
					
					 $seas=null;
					foreach($conf['seas'] as $seas_reg=>$s)
					{
						if($seas_reg>$seas)
						 $seas=$seas_reg;
					}

					 $items[$url_reg.'/'.$seas] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'db_cover_page/index.php?db='.$url_reg.'&ss='.$seas,
					 'title' => t($conf['title']),
					 'access' => user_access('access performance analysis'),
					 'type' => MENU_NORMAL_ITEM,
					 'weight' => 1);
					 
					 $title=(($conf['settings']['cntry']!='')?$conf['settings']['cntry']:'').(($conf['settings']['cntry']!='' & $conf['settings']['lsc']!='')?'-':'').(($conf['settings']['lsc']!='')?$conf['settings']['lsc']:''); 
					 
					 $items[$url_reg.'/'.$seas.'/seasons'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/seasons/index.php?db='.$url_reg.'&ss='.$seas,
					      'title' => t('Select Seasons '.$value),
					      'access' => user_access('access performance analysis'),
					      'type' => MENU_NORMAL_ITEM,
					      'weight' => -5);
					 
					 $items[$url_reg.'/'.$seas.'/meets'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/meets/index.php?db='.$url_reg.'&ss='.$seas,
					      'title' => t('Meets '.$value),
					      'callback' => '',
					      'access' => user_access('access performance analysis'),
					      'type' => MENU_NORMAL_ITEM,
					      'weight' => -4);
				
							     
							   
					     $items[$url_reg.'/'.$seas.'/rankings'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/rankings/index.php?db='.$url_reg.'&ss='.$seas,
							      'title' => t($title.' Rankings '.$value),
							      'access' => user_access('access performance analysis'),
							      'type' => MENU_NORMAL_ITEM,
							      'weight' => -3);
				
					     $items[$url_reg.'/'.$seas.'/athlete_times'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/athlete/index.php?db='.$url_reg.'&ss='.$seas,
							      'title' => t('Athlete Times '.$value),
							      'access' => user_access('access performance analysis'),
							      'type' => MENU_NORMAL_ITEM,
							      'weight' => -2);
				
					     $items[$url_reg.'/'.$seas.'/standards'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/standards/index.php?db='.$url_reg.'&ss='.$seas,
							      'title' => t('Standards '.$value),
							      'access' => user_access('access performance analysis'),
							      'type' => MENU_NORMAL_ITEM,
							      'weight' => -1);
				
					     $items[$url_reg.'/'.$seas.'/records'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/records/index.php?db='.$url_reg.'&ss='.$seas,
							      'title' => t('Records '.$value),
							      'access' => user_access('access performance analysis'),
							      'type' => MENU_NORMAL_ITEM,
							      'weight' => 0);
						
				
						$items[$url_reg.'/'.$seas.'/fina_points'] = array('path' => 'http://'.$conf['url'].'/'.$perfanal_url.'main/fina/index.php?db='.$url_reg.'&ss='.$seas,
								 'title' => t('Fina Points'),
								 'access' => user_access('access performance analysis'),
								 'type' =>MENU_NORMAL_ITEM,
								 'weight' => 6);
						 /*
						 $items[$url_reg.'/'.$seas.'/layout'] = array(
						    'title' => 'Perfanal '.$url_reg.' Layout (Disable)',
						    'page callback' => 'Performance_Anaylsis_layout',
						    'access arguments' => array('layout performance analysis (everyone)'),
						    'type' => MENU_NORMAL_ITEM,'weight' => 10);*/
						    
						     $items[$url_reg.'/layout'] = array(
						    'title' => 'Perfanal '.$url_reg.' Layout (Disable)',
						    'page callback' => 'Performance_Anaylsis_layout',
						    'access arguments' => array('layout performance analysis (everyone)'),
						    'type' => MENU_NORMAL_ITEM,'weight' => 10);

					 }
				 }
			 }
	
	return $items;
}

function Performance_Anaylsis_layout()
{
	drupal_set_title('');
	drupal_set_breadcrumb(array('breadcrumb0123456789'));
	return	'page_contents0123456789';
}


function Performance_Anaylsis_block($op = 'list', $delta = 0, $edit = array()) {
 switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Automated scroll Record Breakers');
      return $blocks;
    case 'configure':
      $form = array();
      if ($delta == 0) {
        $form['perfanal_v2_records_breakers_atonce'] = array(
          '#type' => 'textfield',
          '#title' => t('Display number'),
          '#size' => 2,
          '#description' => t('This is the amount of records to display at once.'),
          '#default_value' =>variable_get('perfanal_v2_records_breakers_atonce',  8)
        );
	$form['perfanal_v2_records_breakers_db'] = array(
          '#type' => 'textfield',
          '#title' => t('Database'),
          '#size' => 20,
          '#description' => t('This is the database to pull the records from.'),
          '#default_value' =>variable_get('perfanal_v2_records_breakers_db',  '')
        );
      }
      return $form;
    case 'save':
       if ($delta == 0) {
        // Have Drupal save the string to the database.
        variable_set('perfanal_v2_records_breakers_atonce', $edit['perfanal_v2_records_breakers_atonce']);
	 variable_set('perfanal_v2_records_breakers_db', $edit['perfanal_v2_records_breakers_db']);
      }
      return;
    case 'view': default:
      // If $op is "view", then we need to generate the block for display
      // purposes. The $delta parameter tells us which block is being requested.
      switch ($delta) {
        case 0:
          $block['subject'] =  'Congratulations to the following Record Breakers';
          $block['content'] = block_Performance_Anaylsis_record_breakers();
          break;
      }
      return $block;
  }
}

function block_Performance_Anaylsis_record_breakers()
{
	global $perfanal_url;
	$domain = $_SERVER["SERVER_NAME"];
	$db_breakers = variable_get('perfanal_v2_records_breakers_db',  '');
	
	   require($perfanal_url.'main_config.php');
	    
	 foreach($sites as $domain_reg=>$data)
	 {
		
		 if(preg_match('/'.$domain_reg.'/',$domain))
		 {
			 foreach($data as $url_reg=>$conf)
			 {
				 if($db_breakers == $url_reg)
				 {
					 $seas=null;
					foreach($conf['seas'] as $seas_reg=>$s)
					{
						if($seas_reg>=$seas)
						 $seas=$seas_reg;
					}
					break;
				 }
			 
			 }
		 }
	 }
	 
	
	 
	 	
	     $output="<div id='record_breakers'><input type='hidden' id='record_url' value='http://".$conf['url'].'/'.$perfanal_url."main/records/record_breakers.php?db=".$db_breakers.'&ss='.$seas."&size=".variable_get('perfanal_v2_records_breakers_atonce',  8)."&loc=../".$perfanal_url."'></div>";
	     
	     return $output;	
}

drupal_add_js($perfanal_url.'js/ajax.js',null,'footer',true);
drupal_add_js($perfanal_url.'js/records.js',null,'footer',true);



?>
